repos:
- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
  - id: isort
    args: ["--filter-files"]
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    language_version: python3.10
