version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8080:8080"
    # volumes:
    #   - .:/app
    #   - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
    volumes:
    - redis-db:/data
volumes:
  redis-db: {}
# volumes:
#   logvolume01: {}
