name: CI

on:
  push:
    branches:
      - 'main'
      - '[0-9].[0-9]+'  # matches to backport branches, e.g. 3.6
    tags: [ 'v*' ]
  pull_request:
    branches:
      - 'main'
      - '[0-9].[0-9]+'
  schedule:
    - cron:  '0 6 * * *'  # Daily 6AM UTC build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:

  lint:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Cache PyPI
      uses: actions/cache@v2.1.7
      with:
        key: pip-lint-${{ hashFiles('pyproject.toml') }}
        path: ~/.cache/pip
        restore-keys: |
            pip-lint-
    - name: Update pip, wheel, setuptools, poetry
      run: |
        python -m pip install -U pip wheel setuptools poetry
    - name: Install self
      run: |
        poetry install
    - name: Run linters
      run: |
        make lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"    # - name: Cache
    - name: Cache PyPI
      uses: actions/cache@v2.1.7
      with:
        key: pip-ci-${{ hashFiles('pyproject.toml') }}
        path: ${{ steps.pip-cache.outputs.dir }}
        restore-keys: |
            pip-ci-
    - name: Update pip, wheel, setuptools, poetry
      run: |
        python -m pip install -U pip wheel setuptools poetry
    - name: Install self
      run: |
        poetry install
    - name: Run tests
      run: |
        make vvtest
